name: Build Codle MCP Dev

on:
  push:
    branches: [develop]

jobs:
  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@main
    with:
      env: dev
      target: develop
      updateTargets: |
        {
          "aws": {
            "imageName": "jce-ecr-codle-mcp-all-dev",
            "valueFilePath": ["codle-mcp/aws-apne2-dev-service.yaml"]
          }
        }
    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
