name: Build Codle MCP Prd

on:
  push:
    branches: [ main ]

jobs:

  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@main
    with:
      env: prd
      target: main
      updateTargets: |
        {
          "aws": {
            "imageName": "jce-ecr-codle-mcp-all-prd",
            "valueFilePath": ["codle-mcp/aws-apne2-prd-service.yaml"]
          }
        }
    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
