name: Prettier

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/*.{js,md,ts,json}
          only_changed: True
